name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code to build server
        uses: actions/checkout@v3
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${ secrets.HOST }
          username: ${ secrets.SSH_USER_NAME }
          port: ${ secrets.SSH_PORT }
          key: ${ secrets.SSH_KEY }
          source: "./*"
          target: "/home/ubuntu/app"
      - name: run nodejs app
        run: |
            cd /home/ubuntu/app
            node run server.js